### Adapted from the '.fzf.zsh' that gets autogenerated if you run fzf's install script
### It leverages the "FZF_HOME" env var that we export in the'xx_fzf.sh' script

# Setup fzf
# ---------
if [[ ! "$PATH" == *${FZF_HOME}/bin* ]]; then
  export PATH="${PATH:+${PATH}:}${FZF_HOME}/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "${FZF_HOME}/shell/completion.zsh" 2> /dev/null

# Key bindings
# ------------
source "${FZF_HOME}/shell/key-bindings.zsh"


### Here are some extra previews for the ohmyzsh 'fzf-tab' plugin (see .antigenrc)

# Preview systemd unit status
zstyle ':fzf-tab:complete:systemctl-*:*' fzf-preview 'SYSTEMD_COLORS=1 sudo systemctl status $word'

# Preview contents of variables export, unset
zstyle ':fzf-tab:complete:(-command-|-parameter-|-brace-parameter-|export|unset|expand):*' fzf-preview 'echo ${(P)word}'

# Preview process details for 'kill' and 'ps' commands
zstyle ':completion:*:*:*:*:processes' command "\ps -u $USER -o pid,user,comm -w -w"
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-preview \
  '[[ $group == "[process ID]" ]] && \ps --pid=$word -o cmd --no-headers -w -w'
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-flags --preview-window=down:3:wrap
