### Adapted from the '.fzf.bash' that gets autogenerated if you run fzf's install script
### The goal was to abstract the FZF location. This works well if you manage fzf via asdf 

FZF_HOME=""

fzf_location=$(which fzf)
if [[ "$fzf_location" == *shims* ]]; then
  # fzf is a shim (ie. managed by asdf), so ask asdf what the actual location is
  fzf_location=$(asdf which fzf)
fi

# Get the path two directories up
FZF_HOME="$(dirname $(dirname ${fzf_location}))"

# Setup fzf
# ---------
if [[ ! "$PATH" == *${FZF_HOME}/bin* ]]; then
  export PATH="${PATH:+${PATH}:}${FZF_HOME}/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "${FZF_HOME}/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "${FZF_HOME}/shell/key-bindings.bash"

