### Adapted from the '.fzf.bash' that gets autogenerated if you run fzf's install script
### It leverages the "FZF_HOME" env var that we export in the'xx_fzf.sh' script

# Setup fzf
# ---------
if [[ ! "$PATH" == *${FZF_HOME}/bin* ]]; then
  export PATH="${PATH:+${PATH}:}${FZF_HOME}/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "${FZF_HOME}/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "${FZF_HOME}/shell/key-bindings.bash"
